module.exports = {
  "couponWrap": "coupon-module__couponWrap___3NWp0",
  "couponW": "coupon-module__couponW___33gyl",
  "leftTagW": "coupon-module__leftTagW___l7p2a",
  "couponLeftIcon": "coupon-module__couponLeftIcon___JveMf",
  "leftTagIcon": "coupon-module__leftTagIcon___21MB-",
  "rightTag": "coupon-module__rightTag___3t0K4",
  "circleIconW": "coupon-module__circleIconW___X71vJ",
  "expireTag": "coupon-module__expireTag___27xOR",
  "couponT": "coupon-module__couponT___1_aMU",
  "priceContent": "coupon-module__priceContent___3crrO",
  "couponL": "coupon-module__couponL___1iMaZ",
  "couponC": "coupon-module__couponC___2rfKR",
  "couponR": "coupon-module__couponR___38WCh",
  "button": "coupon-module__button___3Qa-w",
  "buttonText": "coupon-module__buttonText___3VGpc",
  "couponB": "coupon-module__couponB___RUj4S",
  "dashedLine": "coupon-module__dashedLine___1fGR8",
  "couponDetail": "coupon-module__couponDetail___2jA7I",
  "_couponBLine": "coupon-module___couponBLine___VTDU2",
  "_leftTag": "coupon-module___leftTag___3haq-",
  "_rightTag": "coupon-module___rightTag___2DmVo",
  "couponLimit": "coupon-module__couponLimit___j7h7Z",
  "couponTitle": "coupon-module__couponTitle___C981f",
  "couponBtnTitOther": "coupon-module__couponBtnTitOther___3arUf"
};
