module.exports = {
  "rules": "index-module__rules___1rffp",
  "phone": "index-module__phone___a9Mej",
  "myPopUp": "index-module__myPopUp___35l3m",
  "closeStyle": "index-module__closeStyle___2DGP9",
  "popRules": "index-module__popRules___1KbSM",
  "banner": "index-module__banner___2pYYA",
  "rights": "index-module__rights___30OrB",
  "goods": "index-module__goods___kDgW_",
  "btn": "index-module__btn___2wzGo",
  "btn_normal": "index-module__btn_normal___zT4si",
  "btn_gray": "index-module__btn_gray___-YrSV",
  "description": "index-module__description___15ugm",
  "descriptionBig": "index-module__descriptionBig___3uTOR",
  "mTop40": "index-module__mTop40___32ffB",
  "infoBox": "index-module__infoBox___2JJsr",
  "num": "index-module__num___3A4GV",
  "popWrap": "index-module__popWrap___Vrdnf",
  "popWrapHasBtn": "index-module__popWrapHasBtn___3tHe_",
  "popWrapNotBtn": "index-module__popWrapNotBtn___fmgiB",
  "popTop": "index-module__popTop___1b9Vq",
  "popCard": "index-module__popCard___3H-L0",
  "popBtn": "index-module__popBtn___3h073"
};
