module.exports = {
  "banner": "index-module__banner___3ejRh",
  "rights": "index-module__rights___2cwVs",
  "goods": "index-module__goods___3VSSU",
  "btn": "index-module__btn___7AswP",
  "btn_normal": "index-module__btn_normal___2r8QU",
  "move": "index-module__move___1_F7T",
  "btn_gray": "index-module__btn_gray___21iei",
  "phone": "index-module__phone___1ojeE",
  "description": "index-module__description___3SYzT",
  "descriptionBig": "index-module__descriptionBig___2h_Pz",
  "infoBox": "index-module__infoBox___2DfJN",
  "num": "index-module__num___38sBL",
  "codeInputBox": "index-module__codeInputBox___M0cLm",
  "codeInput": "index-module__codeInput___3PP4v",
  "popWrap": "index-module__popWrap___3g5tA",
  "popWrapHasBtn": "index-module__popWrapHasBtn___2nhnv",
  "popTop": "index-module__popTop___3i_kO",
  "popCard": "index-module__popCard___M7yii"
};
