module.exports = {
  "contentNew": "index-module__contentNew___2kQhC",
  "titleCont2": "index-module__titleCont2___2HjTQ",
  "active": "index-module__active___1Szgs",
  "item": "index-module__item___1cSU5",
  "left": "index-module__left___1bnRu",
  "right": "index-module__right___1nAja",
  "newImg": "index-module__newImg___1ibQL",
  "user": "index-module__user___rJq7b",
  "newNickName": "index-module__newNickName___1rNWb",
  "newAmount": "index-module__newAmount___2XZ9r",
  "newDate": "index-module__newDate___1OKP2",
  "newFlag": "index-module__newFlag___Ltr-P",
  "noData": "index-module__noData___3eOi3",
  "more": "index-module__more___1JbxH",
  "down": "index-module__down___1YAdy",
  "up": "index-module__up___1CDSm",
  "autoHeight": "index-module__autoHeight___18XRb",
  "maxHeight": "index-module__maxHeight___L7pyo",
  "subTitle": "index-module__subTitle___oQLsR",
  "itemFriend": "index-module__itemFriend___1oYVg",
  "img": "index-module__img___3p3T6",
  "nickName": "index-module__nickName___pjURb",
  "txt": "index-module__txt___6VqJk",
  "shareFriend": "index-module__shareFriend___1j06f"
};
