module.exports = {
  "shops": "index-module__shops___JLp_r",
  "shopsTitle": "index-module__shopsTitle___2XokH",
  "shopsContent": "index-module__shopsContent___2XmOZ",
  "notHint": "index-module__notHint___kOrHI",
  "icon": "index-module__icon___2AHvl",
  "hintTitle": "index-module__hintTitle___3jT4Q",
  "hintSub": "index-module__hintSub___2i2L5",
  "shopsItem": "index-module__shopsItem___1YRee",
  "shopsStore": "index-module__shopsStore___12Gws",
  "shopsStoreImg": "index-module__shopsStoreImg___1O6Xq",
  "shopsStores": "index-module__shopsStores___2bBVX",
  "shopsName": "index-module__shopsName___Eexwq",
  "shopsHint": "index-module__shopsHint___1epd0",
  "shopsStorsInfo": "index-module__shopsStorsInfo___MupJZ",
  "shopsStarAndSales": "index-module__shopsStarAndSales___12oyx",
  "segmentLine": "index-module__segmentLine___1EhLQ",
  "daDaExpress": "index-module__daDaExpress___2SR_O",
  "freightWordsText": "index-module__freightWordsText___1JKlc",
  "freightWordsTextMargin": "index-module__freightWordsTextMargin___22Rvz",
  "shopsStorsMargin": "index-module__shopsStorsMargin___2Reb3",
  "couponTagCase": "index-module__couponTagCase___3PFfI",
  "couponCommon": "index-module__couponCommon___2Ffhv",
  "left_radio": "index-module__left_radio___fuAGF",
  "right_radio": "index-module__right_radio___1fdOI",
  "couponContainer": "index-module__couponContainer___3mvKl"
};
