module.exports = {
  "goodListLteTwoBox": "index-module__goodListLteTwoBox___2OaZ4",
  "rowItemBox": "index-module__rowItemBox___3mqGu",
  "itemPicture": "index-module__itemPicture___2XhMz",
  "itemTitleBox": "index-module__itemTitleBox___pTP_t",
  "itemTitle": "index-module__itemTitle___39Ivr",
  "itemCurrentPrice": "index-module__itemCurrentPrice___3Cc03",
  "itemPrice": "index-module__itemPrice___17k_9",
  "addPurchaseBox": "index-module__addPurchaseBox___2Vx6R",
  "goodListEtThreeBox": "index-module__goodListEtThreeBox___R5wwd",
  "goodListEtThreeItem": "index-module__goodListEtThreeItem___3Phe6",
  "goodListEtThreeItemPicture": "index-module__goodListEtThreeItemPicture___3qxam",
  "goodListEtThreeItemTitle": "index-module__goodListEtThreeItemTitle___2YUQk",
  "goodListEtThreeItemCurrentPrice": "index-module__goodListEtThreeItemCurrentPrice___DT2xF",
  "goodListEtThreeItemPrice": "index-module__goodListEtThreeItemPrice___25ero",
  "goodListGtThreeBox": "index-module__goodListGtThreeBox___13eG4",
  "goodListGtThree": "index-module__goodListGtThree___3qdGt",
  "goodItem": "index-module__goodItem___AxYxT",
  "goodItemLast": "index-module__goodItemLast___2cbMC",
  "goodListGtThreeItemFirst": "index-module__goodListGtThreeItemFirst___2boXL",
  "goodListGtThreeItem": "index-module__goodListGtThreeItem___nu-1f",
  "goodListGtThreeItemPicture": "index-module__goodListGtThreeItemPicture___UjCIi",
  "goodListGtThreeItemTitle": "index-module__goodListGtThreeItemTitle___1J-b5",
  "goodListGtThreeItemCurrentPrice": "index-module__goodListGtThreeItemCurrentPrice___1OiRL",
  "goodListGtThreeItemPrice": "index-module__goodListGtThreeItemPrice___1yX8e"
};
