module.exports = {
  "vipDayBox": "member-module__vipDayBox___2Xs7n",
  "platformCoupon": "member-module__platformCoupon___1Sbt4",
  "item": "member-module__item___-Bmyl",
  "titleBox": "member-module__titleBox___1IL1Z",
  "title1": "member-module__title1___fD-Gf",
  "subT": "member-module__subT___3le82",
  "openMore": "member-module__openMore___Rmb-t",
  "couB": "member-module__couB___2Ncen",
  "couponLimit": "member-module__couponLimit___VK_er",
  "itemBox": "member-module__itemBox___2Xtck",
  "price": "member-module__price___2cDGP",
  "yuan": "member-module__yuan___yJ53w",
  "useRemark": "member-module__useRemark___14xKR",
  "descrip": "member-module__descrip___1IyP5",
  "btnText": "member-module__btnText___AeCsA",
  "btnTextDis": "member-module__btnTextDis___1bKuY",
  "btnTextuse": "member-module__btnTextuse___2LiEq",
  "overIcon": "member-module__overIcon___1IxCh",
  "progress": "member-module__progress___1b5pY",
  "bar": "member-module__bar___1gtcz",
  "currentProgree": "member-module__currentProgree___qZSJ5",
  "barText": "member-module__barText___2uNUB"
};
