module.exports = {
  "isLoading": "index-module__isLoading___2fhbD",
  "isLoadingImg": "index-module__isLoadingImg___1KaRS",
  "isBottom": "index-module__isBottom___3vqM1",
  "content": "index-module__content___2TfsM",
  "title": "index-module__title___3NEBf",
  "listBox": "index-module__listBox___2jBB1",
  "listLeft": "index-module__listLeft___3DCRE",
  "logo": "index-module__logo___g4FrJ",
  "listCenter": "index-module__listCenter___rGqve",
  "money": "index-module__money___rNLNe",
  "orderNo": "index-module__orderNo___2l7S8",
  "listRt": "index-module__listRt___2D6wQ",
  "date": "index-module__date___Ej48P",
  "status": "index-module__status___3brl3",
  "status_wait": "index-module__status_wait___2hfNv",
  "status_refund": "index-module__status_refund___1gEd5",
  "status_end": "index-module__status_end___20fAC",
  "margin_btm30": "index-module__margin_btm30___1D0F8",
  "center": "index-module__center___3ccEb",
  "toCharge": "index-module__toCharge___3yEBC",
  "noDataImg": "index-module__noDataImg___ONvSE",
  "noData": "index-module__noData___3Hkkh",
  "bg_white": "index-module__bg_white___1SI8L"
};
