module.exports = {
  "myExchangePage": "index-module__myExchangePage___1PvCu",
  "exchangeBlock": "index-module__exchangeBlock___3WHTe",
  "img": "index-module__img___hXmjk",
  "skuImg": "index-module__skuImg___1D18v",
  "msgBlock": "index-module__msgBlock___p0pQg",
  "btn": "index-module__btn___3gPfv",
  "toUse": "index-module__toUse___1wDLI",
  "beansNum": "index-module__beansNum___25_mj",
  "beansText": "index-module__beansText___1i5Jw",
  "priceSpan": "index-module__priceSpan___31KIU",
  "title": "index-module__title___3Ykgw",
  "code_title": "index-module__code_title___2vjRT",
  "des": "index-module__des___2y9Fp",
  "availableDate": "index-module__availableDate___jDQmT",
  "dash": "index-module__dash___10JGG",
  "toExchangeBtn": "index-module__toExchangeBtn___376Kj",
  "exchanging": "index-module__exchanging___1j9Eu",
  "exchangeBlockDrak": "index-module__exchangeBlockDrak___1wWDi",
  "used": "index-module__used___1GXmW",
  "overTime": "index-module__overTime___3Nwy_",
  "usedImg": "index-module__usedImg___2_Vv7",
  "overTimeImg": "index-module__overTimeImg___28lZt"
};
