module.exports = {
  "coupons": "index-module__coupons___1G2DU",
  "title": "index-module__title___oviLC",
  "plan_hint": "index-module__plan_hint___3b9vr",
  "pecket": "index-module__pecket___3--hc",
  "bottom_triangle": "index-module__bottom_triangle___2Ut0x",
  "icon": "index-module__icon___39Jx0",
  "text": "index-module__text___1y5QX",
  "schedule": "index-module__schedule___2uKXc",
  "login_btn": "index-module__login_btn___3cKcJ",
  "scrollView": "index-module__scrollView___2vvvq",
  "sheet_coupon": "index-module__sheet_coupon___3MZAT",
  "coupon_money": "index-module__coupon_money___2mztR",
  "money_symbol": "index-module__money_symbol___3EWQq",
  "money_count": "index-module__money_count___2AZ8F",
  "money_hint": "index-module__money_hint___wL7Yl",
  "coupon_info": "index-module__coupon_info___1LHGy",
  "name": "index-module__name___2VPA9",
  "condition": "index-module__condition___1n8q7",
  "coupon_used": "index-module__coupon_used___2LxYq",
  "more_coupon": "index-module__more_coupon___1uaF9",
  "clearMargin": "index-module__clearMargin___1MKw-"
};
