module.exports = {
  "content": "index-module__content___ACDC3",
  "title": "index-module__title___2lHh-",
  "title2": "index-module__title2___3g1-g",
  "centerTxt": "index-module__centerTxt___1VYNR",
  "centerContent": "index-module__centerContent___1z0I-",
  "people": "index-module__people___1YxnS",
  "imgCont": "index-module__imgCont___3nzQX",
  "icon": "index-module__icon___3dKrb",
  "nickName": "index-module__nickName___18flc",
  "tag": "index-module__tag___1zGCL",
  "txt": "index-module__txt___UrUC4",
  "btnCont": "index-module__btnCont___34tVt",
  "shareBtn": "index-module__shareBtn___2-pTn",
  "subBtn": "index-module__subBtn___365DQ",
  "progressLine": "index-module__progressLine___2RPax",
  "progressLineInnerCont": "index-module__progressLineInnerCont___3vCTs",
  "progressLineInner": "index-module__progressLineInner___2INVf",
  "flag": "index-module__flag___2UycK",
  "target": "index-module__target___3wUAU",
  "text": "index-module__text___1hCw_",
  "animation": "index-module__animation___bpEKg",
  "mymove": "index-module__mymove___2InvT"
};
