module.exports = {
  "pop": "index-module__pop___2N9L2",
  "content": "index-module__content___3gX0Y",
  "pop_exchange": "index-module__pop_exchange___1tpmn",
  "time": "index-module__time___15OT_",
  "buttons": "index-module__buttons___2eNRx",
  "item": "index-module__item___3iKDY",
  "close": "index-module__close___ey4hM",
  "pop_success": "index-module__pop_success___26729",
  "avatar_case": "index-module__avatar_case___3voss",
  "avatar": "index-module__avatar___15cg6",
  "avatar_img": "index-module__avatar_img___2vIdA",
  "name": "index-module__name___1zPWb",
  "pop_success_btn": "index-module__pop_success_btn___3H0y4",
  "pop_invite_btn": "index-module__pop_invite_btn___3ra6e",
  "pop_invite": "index-module__pop_invite___2qHAc",
  "title": "index-module__title___2RF5L",
  "sub_title": "index-module__sub_title___1Ic9M",
  "red": "index-module__red___2ehnK",
  "invite_time": "index-module__invite_time___1JRIz"
};
