module.exports = {
  "rule_box": "index-module__rule_box___29-SF",
  "rule_tab": "index-module__rule_tab___3qcLx",
  "coupon_box": "index-module__coupon_box___382p7",
  "coupon_left": "index-module__coupon_left___2u218",
  "shiwu_img": "index-module__shiwu_img___1knvg",
  "coupon_lr": "index-module__coupon_lr___3Obe3",
  "value_unit": "index-module__value_unit___ltgkS",
  "value": "index-module__value___1wlcI",
  "price2": "index-module__price2___q5tKW",
  "value_zhe": "index-module__value_zhe___3mic1",
  "zhe_unit": "index-module__zhe_unit___1BdUG",
  "title_box": "index-module__title_box___fNaXs",
  "title": "index-module__title___2bU4S",
  "use_door": "index-module__use_door___quUGy",
  "time": "index-module__time___5AhXe",
  "coupon_right": "index-module__coupon_right___-bifw",
  "use_button": "index-module__use_button___LCRm2",
  "money_bg": "index-module__money_bg___29l37",
  "money_bg_2": "index-module__money_bg_2___2h_Nn",
  "null_box": "index-module__null_box___2Q2-t",
  "null_bg": "index-module__null_bg___1C1ps",
  "null_text": "index-module__null_text___1CWsn",
  "goCity": "index-module__goCity___1aoXp",
  "loading": "index-module__loading___gOmBD",
  "loading_img": "index-module__loading_img___1fA3h"
};
