module.exports = {
  "topBox": "index-module__topBox___1mHmW",
  "rules": "index-module__rules___2kdmR",
  "banner": "index-module__banner___tAy-V",
  "topTxt": "index-module__topTxt___1Sbjf",
  "centerBox": "index-module__centerBox___19x5z",
  "move": "index-module__move___2Ys5K",
  "centerTitle": "index-module__centerTitle___3YskN",
  "toDaojia": "index-module__toDaojia___ZCgNW",
  "btmImgBox": "index-module__btmImgBox___2aSnE",
  "btmImg": "index-module__btmImg___3rh11",
  "getButton": "index-module__getButton___3pxLy",
  "couponBox": "index-module__couponBox___2_rYc",
  "couponMon": "index-module__couponMon___IchyA",
  "bigMon": "index-module__bigMon___2Yuh4",
  "couponContent": "index-module__couponContent___2PJT9",
  "couponTitle": "index-module__couponTitle___2BClf",
  "limitRule": "index-module__limitRule___3rm_i",
  "limitDate": "index-module__limitDate___jgZD2",
  "usecouponBtn": "index-module__usecouponBtn___fkKpk",
  "usecouponBtnImg": "index-module__usecouponBtnImg___2AiyK",
  "pop_wrap": "index-module__pop_wrap___YSJvl",
  "ruleTitle": "index-module__ruleTitle___280Jx",
  "rich_txt": "index-module__rich_txt___6-7WU",
  "none_txt": "index-module__none_txt___34NBO"
};
