module.exports = {
  "center": "index-module__center___v4TNT",
  "word_scale2": "index-module__word_scale2___29FOK",
  "layer": "index-module__layer___349wu",
  "txt_space": "index-module__txt_space___2pRU1",
  "main": "index-module__main___3QXK3",
  "close": "index-module__close___1wS_7",
  "title": "index-module__title___24dcG",
  "lists_box": "index-module__lists_box___2GVAN",
  "short_lists": "index-module__short_lists___2f47H",
  "lists": "index-module__lists___3WhpN",
  "item": "index-module__item___29y7i",
  "active": "index-module__active___-UIt7",
  "icon": "index-module__icon___2IpBr",
  "item_title": "index-module__item_title___3KNGO",
  "waters": "index-module__waters___K8wJ2",
  "last_part_item": "index-module__last_part_item___Btq91",
  "mid_part_item": "index-module__mid_part_item___2QlXq",
  "last_reward": "index-module__last_reward___2wj8Z",
  "tips": "index-module__tips___3ptjw",
  "btn": "index-module__btn___1lDl7",
  "btn_fail": "index-module__btn_fail___fkK8H",
  "pre_load": "index-module__pre_load___-kFi5",
  "funcBallLayout": "index-module__funcBallLayout___1kdKT",
  "item_word_color": "index-module__item_word_color___2Rgmn"
};
