module.exports = {
  "dialog": "index-module__dialog___29loT",
  "dialog_bg": "index-module__dialog_bg___1pxcn",
  "container": "index-module__container___37Qau",
  "title": "index-module__title___35WRe",
  "hots_category": "index-module__hots_category___SlXI7",
  "category": "index-module__category___3sgL-",
  "image": "index-module__image___2_WYW",
  "category_image": "index-module__category_image___3CjlR",
  "info": "index-module__info___27fWp",
  "name": "index-module__name___3k_YL",
  "hots_category_btn": "index-module__hots_category_btn___3hUF5",
  "money": "index-module__money___3lfa-",
  "money_text": "index-module__money_text___3VWof",
  "current": "index-module__current___WiSYF",
  "symbol": "index-module__symbol___lAEk8",
  "original": "index-module__original___1z3qT",
  "hots_brn": "index-module__hots_brn___2zkcQ",
  "light": "index-module__light___PU76j",
  "btn": "index-module__btn___3feJh",
  "return_btn": "index-module__return_btn___3I8SH",
  "leave_btn": "index-module__leave_btn___3NO2E"
};
