module.exports = {
  "dialog": "index-module__dialog___ko1VQ",
  "dialog_bg": "index-module__dialog_bg___1OoQh",
  "container": "index-module__container___1-V3l",
  "title": "index-module__title___1_orQ",
  "hots_category": "index-module__hots_category___3VFuF",
  "category": "index-module__category___1MlAo",
  "image": "index-module__image___1X-jM",
  "category_image": "index-module__category_image___1WGb1",
  "info": "index-module__info___1RdNO",
  "name": "index-module__name___3cwa_",
  "hots_category_btn": "index-module__hots_category_btn___34AcF",
  "money": "index-module__money___1gB9u",
  "money_text": "index-module__money_text___2g1y0",
  "current": "index-module__current___3XFvH",
  "symbol": "index-module__symbol___1s39W",
  "original": "index-module__original___ZRNSl",
  "hots_brn": "index-module__hots_brn___416kG",
  "light": "index-module__light___1RRqo",
  "btn": "index-module__btn___1iQV-",
  "return_btn": "index-module__return_btn___2bvc2",
  "leave_btn": "index-module__leave_btn___21XeP"
};
