module.exports = {
  "couponDisablePriceCot": "index-module__couponDisablePriceCot___1qi52",
  "couponDisableY": "index-module__couponDisableY___2xlW1",
  "couponDisablePrice": "index-module__couponDisablePrice___2GIkb",
  "couponMain": "index-module__couponMain___2My8c",
  "couponLeftBorder": "index-module__couponLeftBorder____Zx6H",
  "couponRightBorder": "index-module__couponRightBorder___3KEjj",
  "couponLeftMark": "index-module__couponLeftMark___1pwYV",
  "couponRightMark": "index-module__couponRightMark___3fN9T",
  "couponRightMarkSpe": "index-module__couponRightMarkSpe___1R1VU",
  "couponMiddle": "index-module__couponMiddle___1TVax",
  "couponMiddleSingle": "index-module__couponMiddleSingle___1_09z",
  "couponSingleLeft": "index-module__couponSingleLeft___2ze7D",
  "couponSingleRight": "index-module__couponSingleRight___2xIM2",
  "couponDisablePriceCotSingle": "index-module__couponDisablePriceCotSingle___3LGtJ",
  "couponDisablePriceCotTop": "index-module__couponDisablePriceCotTop___3o-Uo",
  "couponTitle": "index-module__couponTitle___lU6vF",
  "couponTitleTopSingle": "index-module__couponTitleTopSingle___3VcV6",
  "couponTitleTop": "index-module__couponTitleTop___1_C8Y",
  "couponStatusTitle": "index-module__couponStatusTitle___2WDEK",
  "couponStatusTitleSingle": "index-module__couponStatusTitleSingle___MhCfG",
  "couponStatusTitleSingleSpe": "index-module__couponStatusTitleSingleSpe___2GMzP",
  "couponStatusTitleBottom": "index-module__couponStatusTitleBottom___1hV_n",
  "couponStatusTitleTop": "index-module__couponStatusTitleTop___2alpe",
  "couponCountDown": "index-module__couponCountDown___2Sx9X",
  "couponCountDownSingle": "index-module__couponCountDownSingle___1JsU0"
};
