module.exports = {
  "redBg": "index-module__redBg___3zwsr",
  "bigNoLogin": "index-module__bigNoLogin___3ui2k",
  "padTop": "index-module__padTop___1wZSF",
  "topLogo": "index-module__topLogo___mRQsP",
  "topLogoNo": "index-module__topLogoNo___3-6VV",
  "noCouponBox": "index-module__noCouponBox___LWEu9",
  "move": "index-module__move___1wh_s",
  "toDaojiaBtn": "index-module__toDaojiaBtn___XhZ72",
  "coupon1Box": "index-module__coupon1Box___3b4T7",
  "useBtn": "index-module__useBtn___2CECE",
  "unloginBtn": "index-module__unloginBtn___1JuF9",
  "coupon": "index-module__coupon___g7sZo",
  "moneyBox": "index-module__moneyBox___1LffC",
  "money": "index-module__money___nM8oH",
  "unit": "index-module__unit___1krY6",
  "rule": "index-module__rule___1RzEh",
  "time": "index-module__time___27mL6",
  "warningTxt": "index-module__warningTxt___3xeOw",
  "btnBox": "index-module__btnBox___1LreL",
  "cancel": "index-module__cancel___r3JuJ",
  "confirm": "index-module__confirm___1-zGl",
  "coupon2Box": "index-module__coupon2Box___mC2jT",
  "couponWrap": "index-module__couponWrap___2dj6Y"
};
