module.exports = {
  "red_mainBox": "index-module__red_mainBox___2C_zW",
  "red_main": "index-module__red_main___2Mrw-",
  "redlottieBg": "index-module__redlottieBg___1cv2X",
  "msg": "index-module__msg___3TMgz",
  "layer_btn": "index-module__layer_btn___6lIfi",
  "redDropLayout": "index-module__redDropLayout___1ZU3-",
  "redGetText": "index-module__redGetText___2Bcu4",
  "red_layer": "index-module__red_layer___23pFJ",
  "content": "index-module__content___2HiRk",
  "re_stroke": "index-module__re_stroke___37VBQ",
  "lott_bg": "index-module__lott_bg___2GTco",
  "rotate_weapp": "index-module__rotate_weapp___1shMB",
  "rotate1": "index-module__rotate1___2CWlB",
  "rise_light": "index-module__rise_light___4VokJ",
  "move": "index-module__move___2o_5O",
  "rise": "index-module__rise___1T4Sw",
  "scale": "index-module__scale___3laJb",
  "red_box_lottie": "index-module__red_box_lottie___3JQ46",
  "redDropText": "index-module__redDropText___3_iTM",
  "white_stroke": "index-module__white_stroke___1fegh",
  "red_box_nofinish_layout": "index-module__red_box_nofinish_layout___1SErZ",
  "red_box_nofinish_t1": "index-module__red_box_nofinish_t1___1xQhr",
  "red_box_nofinish_t2": "index-module__red_box_nofinish_t2___3d-kt",
  "red_box_nofinish_t3": "index-module__red_box_nofinish_t3___3M9YR",
  "red_box_nofinish_img": "index-module__red_box_nofinish_img___2ESV2"
};
