module.exports = {
  "hour_red": "index-module__hour_red___263wC",
  "red_box": "index-module__red_box___-w1-r",
  "red_content": "index-module__red_content___3B9lz",
  "red_time": "index-module__red_time___2fGoQ",
  "red_time_box": "index-module__red_time_box___2WhZ8",
  "red_line": "index-module__red_line___tfjhN",
  "red_bg": "index-module__red_bg___1EbR-",
  "state_desc": "index-module__state_desc___3M2Ik",
  "max_money": "index-module__max_money___1tbLe",
  "max_text": "index-module__max_text___F-Du3",
  "middle_text": "index-module__middle_text___2_MC5",
  "button_box": "index-module__button_box___C1lVd",
  "button_time": "index-module__button_time___2LvKa",
  "left_chance": "index-module__left_chance___1MjCT",
  "end_box": "index-module__end_box___Wk06K",
  "end_text": "index-module__end_text___3-F8F",
  "end_sub_text": "index-module__end_sub_text___6iMb-",
  "hand_box": "index-module__hand_box___3bNF8",
  "hand_img": "index-module__hand_img___1RNHY",
  "mymove": "index-module__mymove___3OYdd",
  "container": "index-module__container___2xuBZ",
  "wave": "index-module__wave___36wZD",
  "circle": "index-module__circle___2uVGK",
  "circle_2": "index-module__circle_2___3pnZ8",
  "circle-opacity": "index-module__circle-opacity___36cWu",
  "circle2-opacity": "index-module__circle2-opacity___3m28c"
};
