module.exports = {
  "box": "index-module__box___3Ds8w",
  "title": "index-module__title___2u1oc",
  "main": "index-module__main___2VLXZ",
  "left": "index-module__left___G1jCS",
  "left_icon": "index-module__left_icon___3YMdW",
  "left_txt": "index-module__left_txt___2cFWd",
  "left_num": "index-module__left_num___3VfoN",
  "left_msg": "index-module__left_msg___3joQA",
  "arrow": "index-module__arrow___nt04b",
  "right": "index-module__right___1HpP4",
  "right_icon": "index-module__right_icon___1iCFe",
  "right_txt": "index-module__right_txt___1vrKM",
  "right_num": "index-module__right_num___3sbXF",
  "right_msg": "index-module__right_msg___1g0v7",
  "footer": "index-module__footer___2MmBB",
  "line": "index-module__line___3Z37h",
  "active": "index-module__active___2su7q",
  "point": "index-module__point___1HAGQ",
  "point_title": "index-module__point_title___3v5mX",
  "scale_font": "index-module__scale_font___Xa6y1",
  "tips": "index-module__tips___1u2tc",
  "tips_bean": "index-module__tips_bean___2n6Ix",
  "tips_num": "index-module__tips_num___2sbQX"
};
