module.exports = {
  "box": "index-module__box___R-ikz",
  "btn": "index-module__btn___1mVaU",
  "defaultTips": "index-module__defaultTips___2VqMC",
  "image": "index-module__image___3pMlK",
  "loading": "index-module__loading___20Y39",
  "loading_img": "index-module__loading_img___2WqbG",
  "login_img": "index-module__login_img___2owHf",
  "location_default": "index-module__location_default___BYRO0",
  "location_default_img": "index-module__location_default_img___2HuKX",
  "location_default_tips": "index-module__location_default_tips___107pX",
  "location_default_btns": "index-module__location_default_btns___3ftYX",
  "location_default_btn": "index-module__location_default_btn___1D7vr",
  "rules": "index-module__rules___9CymM",
  "taskMask": "index-module__taskMask___2tK_2",
  "main_botton": "index-module__main_botton___1aeJJ",
  "content": "index-module__content___3oKUN",
  "button_box": "index-module__button_box___2xRGH",
  "ziyuan": "index-module__ziyuan___3cynZ",
  "baoxiang": "index-module__baoxiang___3wcSh",
  "openBox": "index-module__openBox___3MRnP",
  "lotteryImage": "index-module__lotteryImage___249uz"
};
