module.exports = {
  "newgetbox": "index-module__newgetbox___3R6vQ",
  "newgetmainBox": "index-module__newgetmainBox___fbnl6",
  "newupdatelottieBg": "index-module__newupdatelottieBg___9_MfM",
  "newgetmain": "index-module__newgetmain___39ruZ",
  "newgettree": "index-module__newgettree___2MCLg",
  "newgetbu": "index-module__newgetbu___ujYSb",
  "newgetbu_weapp": "index-module__newgetbu_weapp___2FhBE",
  "newgetlayout": "index-module__newgetlayout___11w7V",
  "newgetlayout_weapp": "index-module__newgetlayout_weapp___By-FM",
  "newgettext1": "index-module__newgettext1___3XJy2",
  "newgetimg": "index-module__newgetimg___3WBeO",
  "msg": "index-module__msg___37VXc",
  "layer_btn": "index-module__layer_btn___qaiuE",
  "newgetlayer": "index-module__newgetlayer___2GaQN",
  "content": "index-module__content___2u3wh",
  "re_stroke": "index-module__re_stroke___3d4fC",
  "lott_bg": "index-module__lott_bg___1s44D",
  "rotate_weapp": "index-module__rotate_weapp___3YMM1",
  "rotate1": "index-module__rotate1___MNzjJ",
  "rise_light": "index-module__rise_light___2KmKk",
  "move": "index-module__move___GLiQv",
  "rise": "index-module__rise___1uBA9",
  "scale": "index-module__scale___2VxI7"
};
