module.exports = {
  "pop_wrap": "index-module__pop_wrap___mP7Oc",
  "content": "index-module__content___1R8av",
  "title": "index-module__title___1GmYv",
  "amount": "index-module__amount___1GLDl",
  "knife": "index-module__knife___3-a8X",
  "txt": "index-module__txt___14k69",
  "btnTxt": "index-module__btnTxt___2l-pj",
  "process": "index-module__process___2ohdH",
  "center": "index-module__center___3zqqx",
  "subtitle": "index-module__subtitle___3_4MO",
  "coupon": "index-module__coupon___28AKo",
  "left": "index-module__left___1Lrcw",
  "money": "index-module__money____Ubqm",
  "unit": "index-module__unit___uDDHM",
  "limit": "index-module__limit___1L125",
  "right": "index-module__right___1VWcL",
  "name": "index-module__name___3Aidm",
  "date": "index-module__date___3ZOw6",
  "animation": "index-module__animation___2ye4Z",
  "mymove": "index-module__mymove___32gxR",
  "popTitle2": "index-module__popTitle2___30dZx",
  "newerImg": "index-module__newerImg___3hS7e",
  "shopTBox": "index-module__shopTBox___P3nyr",
  "shopLine": "index-module__shopLine___1j81y",
  "shopTitle": "index-module__shopTitle___tqZz_"
};
