module.exports = {
  "toTurnableBox": "index-module__toTurnableBox___i_1PT",
  "turnable_box": "index-module__turnable_box___3g2Oh",
  "turnable_item": "index-module__turnable_item___3tT3f",
  "turnable_top_layout": "index-module__turnable_top_layout___2ONwz",
  "turnable_top_biao": "index-module__turnable_top_biao___2_XOv",
  "turnable_top_biao_text": "index-module__turnable_top_biao_text___k_ZSO",
  "turnable_item_left": "index-module__turnable_item_left___9vy7c",
  "turnable_left_num": "index-module__turnable_left_num___htROW",
  "turnable_left_money": "index-module__turnable_left_money___3PllS",
  "turnable_item_right": "index-module__turnable_item_right___1Slnj",
  "turnable_right_title": "index-module__turnable_right_title___37IG4",
  "turnable_bean_num": "index-module__turnable_bean_num___1BuAH",
  "turnable_bean_num_again": "index-module__turnable_bean_num_again___HbH6f",
  "turnable_right_limit": "index-module__turnable_right_limit___I1Ky0",
  "turnable_close": "index-module__turnable_close___-x0uF",
  "turnable_top_title": "index-module__turnable_top_title___2fpYQ",
  "turnable_bottom_btn": "index-module__turnable_bottom_btn___2FnLI",
  "turnable_bottom_btn_text": "index-module__turnable_bottom_btn_text___D-0CD"
};
