module.exports = {
  "couponInfo": "index-module__couponInfo___PVrSd",
  "identifyFirst": "index-module__identifyFirst___3MCW0",
  "name": "index-module__name___3nRr-",
  "limit": "index-module__limit___3n14M",
  "moneyCont": "index-module__moneyCont___2ah-6",
  "cash": "index-module__cash___BOXlh",
  "useBtn": "index-module__useBtn___2lkI_",
  "item": "index-module__item___1PVz4",
  "left": "index-module__left___2t6po",
  "money": "index-module__money___3Vbvz",
  "right": "index-module__right___3cutA",
  "info": "index-module__info___gRJ1l",
  "use": "index-module__use___2u7XO",
  "identify": "index-module__identify___1PPnP",
  "vipCont": "index-module__vipCont___Ej52Z",
  "vipLeft": "index-module__vipLeft___wHeKI",
  "vipIcon": "index-module__vipIcon___3pHfD",
  "vipCenter": "index-module__vipCenter___3ZhOQ",
  "vipInfo": "index-module__vipInfo___2MLF1",
  "vipName": "index-module__vipName___2xVUT",
  "vipLimit": "index-module__vipLimit___1eJDu",
  "vipDate": "index-module__vipDate___2eCZp",
  "vipBtn": "index-module__vipBtn___2QYQ-",
  "animation": "index-module__animation___3Rduo",
  "mymove": "index-module__mymove___1ZuuS"
};
