module.exports = {
  "shops": "index-module__shops___YYvH-",
  "shopsTitle": "index-module__shopsTitle___33sNn",
  "shopsContent": "index-module__shopsContent___1QmBS",
  "notHint": "index-module__notHint___6HeFz",
  "icon": "index-module__icon___Tyzei",
  "hintTitle": "index-module__hintTitle___1LhW0",
  "hintSub": "index-module__hintSub___RT__2",
  "shopsItem": "index-module__shopsItem___2mkS6",
  "shopsStore": "index-module__shopsStore___274Nq",
  "shopsStoreImg": "index-module__shopsStoreImg___OigQD",
  "shopsStores": "index-module__shopsStores___1vKgn",
  "shopsName": "index-module__shopsName___1oqNJ",
  "shopsHint": "index-module__shopsHint___1rG-L",
  "shopsStorsInfo": "index-module__shopsStorsInfo___3wTCA",
  "shopsStarAndSales": "index-module__shopsStarAndSales___3XIPt",
  "segmentLine": "index-module__segmentLine___3E0yb",
  "daDaExpress": "index-module__daDaExpress___3ecnW",
  "freightWordsText": "index-module__freightWordsText___1ci-T",
  "freightWordsTextMargin": "index-module__freightWordsTextMargin___2Skcn",
  "shopsStorsMargin": "index-module__shopsStorsMargin___1FXxb",
  "couponTagCase": "index-module__couponTagCase___3Xkj_",
  "couponCommon": "index-module__couponCommon___3WzfF",
  "left_radio": "index-module__left_radio___39kdV",
  "right_radio": "index-module__right_radio___2QK7P",
  "couponContainer": "index-module__couponContainer___3OoJq"
};
