module.exports = {
  "pop_wrap": "index-module__pop_wrap___1GzBf",
  "content": "index-module__content___3BC7s",
  "title": "index-module__title___24tRh",
  "amount": "index-module__amount___2cdnp",
  "knife": "index-module__knife___3_IHJ",
  "btnTxt": "index-module__btnTxt___3xaID",
  "animation": "index-module__animation___1gami",
  "mymove": "index-module__mymove___23_6A",
  "rightCont": "index-module__rightCont___2CyO_",
  "headIcon": "index-module__headIcon___rwM0C",
  "scrollCont": "index-module__scrollCont___37q-0",
  "rightCoupon": "index-module__rightCoupon___1pU0L",
  "money": "index-module__money___3h1WD",
  "unit": "index-module__unit___2eBga",
  "infoCont": "index-module__infoCont___2fK9a",
  "info": "index-module__info___3mTDw",
  "limitRule": "index-module__limitRule___M-OBO",
  "newIcon": "index-module__newIcon___3uLfX",
  "couponBtn": "index-module__couponBtn___38A06",
  "identify": "index-module__identify___1naY-",
  "bottom": "index-module__bottom___3NvIF",
  "vipCoupon": "index-module__vipCoupon___2m1oL",
  "vipIcon": "index-module__vipIcon___7q0oj",
  "name": "index-module__name___Ra2j5"
};
