module.exports = {
  "topBox": "index-module__topBox___2fjde",
  "rules": "index-module__rules___1LUat",
  "banner": "index-module__banner___u4OKm",
  "topTxt": "index-module__topTxt___1NWbz",
  "centerBox": "index-module__centerBox___2VrPL",
  "move": "index-module__move___Srzhb",
  "centerTitle": "index-module__centerTitle___IXM52",
  "toDaojia": "index-module__toDaojia___11Cio",
  "btmImgBox": "index-module__btmImgBox___3zh9p",
  "btmImg": "index-module__btmImg___1kHaX",
  "getButton": "index-module__getButton___338zU",
  "couponBox": "index-module__couponBox___2MGlR",
  "couponMon": "index-module__couponMon___2-9wv",
  "bigMon": "index-module__bigMon___1J5x4",
  "couponContent": "index-module__couponContent___1OOS3",
  "couponTitle": "index-module__couponTitle___2RtTX",
  "limitRule": "index-module__limitRule___2p1gq",
  "limitDate": "index-module__limitDate___3WfEs",
  "usecouponBtn": "index-module__usecouponBtn___UoMMZ",
  "usecouponBtnImg": "index-module__usecouponBtnImg___2ndUK",
  "pop_wrap": "index-module__pop_wrap___2mCbW",
  "ruleTitle": "index-module__ruleTitle___3gsiH",
  "rich_txt": "index-module__rich_txt___g6CkM",
  "none_txt": "index-module__none_txt___2e7P_"
};
